const HTTP_SUCCESS = 200;
const HTTP_CREATED = 201;
const HTTP_NO_CONTENT = 204;
const HTTP_BAD_REQUEST = 400;
const HTTP_LOGIN_ERROR = 401;
const HTTP_TOKEN_NOT_FOUND = 402;
const HTTP_TOKEN_ERROR = 403
const HTTP_NOT_FOUND = 404;

const HTTP_SERVER_ERROR = 500;


export {
    HTTP_SUCCESS,
    HTTP_NOT_FOUND,
    HTTP_SERVER_ERROR,
    HTTP_BAD_REQUEST,
    HTTP_CREATED,
    HTTP_NO_CONTENT,
    HTTP_LOGIN_ERROR,
    HTTP_TOKEN_NOT_FOUND,
    HTTP_TOKEN_ERROR
}